### ISSUE TITLE
sales_email_shipping_services is not batch safe

### ISSUE THREAD

**Issue by nobodyMO** [netresearch/module-shipping-ui#4]
hi,
we send invoices and labes in an batch job to the customer or print them directly on our network printer. The orders will be processed in a loop on all selected orders in the order grid (mass action). 

During the integration of the dhl plugin in our magento shop we added {{layout handle="sales_email_shipping_services" order_id=$order.entity_id area="frontend"}} to our Mail and invoice templates. If only one invoce is processed, 

If more than one order is processed in one loop, the shipping services information of the first order is used for all following orders. 

The error that causes this behaviour is in the following class:
Netresearch\ShippingUi\ViewModel\Order\Info\ShippingServices.

The method getSelectedServicesByOrderId sets the order to the correct object, but does not delete existing data in $this->selections, 	$this->pickupLocationAddress and $this->serviceOptions. 
Since the properties already contain a value, they are not re-determined in the following, but the old value is simply used in getServiceOptions and getSelections and getPickupLocationAddress. 

So that we don't have to deactivate the plugin again for the time being, I have completely overwritten the class, as the properties are private. 
Please modify the getSelectedServicesByOrderId method as follows. Then I can remove the overwrite again.

```
    public function getSelectedServicesByOrderId(int $orderId): array
    {
        /** @var Order $order */
        $order = $this->orderRepository->get($orderId);
        $this->order = $order;
		$this->selections = null;
		$this->pickupLocationAddress =null;
		$this->serviceOptions = null;

        return $this->getSelectedServices();
    }
```

**Comment by mam08ixo** [comment]
Ew, this view model…

https://github.com/netresearch/module-shipping-ui/blob/f81b79715549844405f1f5102e1dc70957532cd7/ViewModel/Order/Info/ShippingServices.php#L26

Thank you for the detailed explanation. Issue confirmed, we will let you know when a fix is in place.

**Comment by mam08ixo** [comment]
A bugfix [version 2.2.1](https://github.com/netresearch/module-shipping-ui/releases/tag/2.2.1) was released that fixes the issue.
