### ISSUE TITLE
jQXHR.success is deprecated and removed

### ISSUE THREAD

**Issue by in-session** [netresearch/module-shipping-ui#5]
we get the following warning in the console: Netresearch_ShippingUi/js/action/checkout/webapi/get-checkout-data.js:40
[jqXHR.success() and jqXHR.error() are deprecated in jQuery 1.8]

**Comment by mam08ixo** [comment]
Fixed in version [2.3.1](https://github.com/netresearch/module-shipping-ui/releases/tag/2.3.1)
