### ISSUE TITLE
Css class '.admin__page-section-item' does not exist in Magento, yet this module tries to use it

### ISSUE THREAD

**Issue by hostep** [netresearch/module-shipping-ui#6]
The css class `.admin__page-section-item` is being used over here: https://github.com/netresearch/module-shipping-ui/blob/2.3.1/view/adminhtml/web/css/source/_module.less#L501 and was introduced by https://github.com/netresearch/module-shipping-ui/commit/3f480df8ae12ef32261cf4d9a6a1fd3ddc140c1e

As far as I can see, this css class does not exist in Magento core and if you use the [original less.js compiler](https://lesscss.org/usage/), it will complain about this invalid use.
I do see a class `.admin__page-section-item-title` being defined [here in core Magento](https://github.com/magento/magento2/blob/2.3.7/app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/_order.less#L161-L174), maybe this one was meant to be used?

Steps to reproduce:
- Install version 2.3.1 of `netresearch/module-shipping-ui` in a clean Magento installation
- Run: `bin/magento setup:upgrade`
- Run `npm install less@2.7.3`
- Run `rm -R var/view_preprocessed/* pub/static/*`
- Run `bin/magento setup:static-content:deploy -f --theme Magento/backend en_US`
- Run `node_modules/.bin/lessc -l var/view_preprocessed/pub/static/adminhtml/Magento/backend/en_US/css/styles.less` (this lints the less file for validity)
- It will output this error: `extend ' .admin__page-section-item' has no matches`

Would be nice if this oversight could be fixed in a new version as to make your less code 100% valid. Because the backoffice layout breaks a bit when https://github.com/baldwin-agency/magento2-module-less-js-compiler is being used.

Thanks!

**Comment by mam08ixo** [comment]
Hi @hostep, thank you for reporting the issue. This `extend` selector can (and will) be removed with no replacement.

**Comment by mam08ixo** [comment]
A bugfix version [2.3.2](https://github.com/netresearch/module-shipping-ui/releases/tag/2.3.2) was released.

Updating the _Post & DHL Shipping_ extension (`composer update --with-dependencies dhl/shipping-m2`) pulls in the new package version.

**Comment by hostep** [comment]
Awesome, thanks for this quick fix @mam08ixo!
