### ISSUE TITLE
Empty tag doesn't work in some browsers

### ISSUE THREAD

**Issue by HenKun** [netresearch/module-shipping-ui#7]
https://github.com/netresearch/module-shipping-ui/blob/3f2ed27e848a7332618554726fb2586cc5a24ff2/view/frontend/web/template/checkout/address-renderer/delivery-location.html#L2

In this file multiple self-closing `div` and `span` tags are used. PHPStorm reports this as `Empty tag doesn't work in some browsers`.
And indeed, while testing I found an issue related to self-closing `<div /> ` tags (in my own Knockout code) that broke rendering in current Chrome, Knockout failed due to mismatching tags. Changing (in my code)  

`<div class="payment-method-hint" text="getHint()" />`
to
`<div class="payment-method-hint" text="getHint()"></div>`

solved the issue.

I do not know under what conditions exactly this fails, but it failed in one shop in current Chrome.
Also, Magento itself does not use self-closing divs and spans in any vanilla html file.

While searching for other occurences of self-closing divs (`<div[^<]*?/>` and `<span[^<]*?/>`) within the code base, I only found the files `delivery-location.html` and `fieldset.html` in your module.
So while the issue might not be reliably reproducible, it might be worth a change from `<div/>` to `<div></div>` and `<span />` to `<span></span>`

**Comment by mam08ixo** [comment]
Hi @HenKun, thank you for reporting the issue. Execute `composer update --with-dependencies dhl/shipping-m2` to install version [2.4.2](https://github.com/netresearch/module-shipping-ui/releases/tag/2.4.2) of the module with updated Knockout templates.
