### ISSUE TITLE
Netresearch_ShippingUi breaks Stripe 3D-Secure

### ISSUE THREAD

**Issue by tobiasolge** [netresearch/module-shipping-ui#8]
When Netresearch_ShippingUi is enabled, 3D-Secure via StripeIntegration_Payments is not working anymore.
When module Netresearch_ShippingUi is disabled, 3D-Secure is working.

**Comment by ngolatka** [comment]
@tobiasolge Please provide feedback about the open support ticket which you created at Stripe.

**Comment by ngolatka** [comment]
_internal ref: DHLSUP-1064713_

**Comment by tobiasolge** [comment]
Stripe analyzed the problem this module creates! 

What this module does, is that it takes over the order placement process and handles all types of checkout errors as a shipping option validation issue. This is generally bad design for a module, as it would also intercept card declines and every other order placement error, and replace the error message with a shipping options validation error.

It would be best for this module to perform this validation at the shipping page, and not at the payment page. Magento will by default try to save the selected shipping options before it reaches the payment page, and that should be the place to add this validation.

I'd recommend reaching out to Netresearch to explain the issue, they will be in a better position to provide a solution for this.

**Comment by ngolatka** [comment]
Thanks @tobiasolge !

@mam08ixo , could you provide some insights here?

**Comment by mam08ixo** [comment]
@tobiasolge: Do you have a public Magento instance available with Stripe test integration active and the DHL Shipping module enabled? Without being able to reproduce the issue, including a description of what happens vs. what is supposed to happen, it is hard to tell what exactly is causing the incompatibility and how to solve it.

The DHL module does indeed intercept the order placement process, but does not "take over". The original process still gets executed. As noted before, we need to see this in action to assess further.

Thank you

**Comment by tobiasolge** [comment]
I I provided infos via ticket.

**Comment by ngolatka** [comment]
:heavy_check_mark: Info received, we'll check it.

**Comment by mam08ixo** [comment]
Thank you @tobiasolge, we identified the problem and are working on a solution.

**Comment by tobiasolge** [comment]
top, thanks a lot

**Comment by mam08ixo** [comment]
Hi @tobiasolge, thank you for reporting the issue. Execute `composer update --with-dependencies dhl/shipping-m2` to install version [2.4.3](https://github.com/netresearch/module-shipping-ui/releases/tag/2.4.3) of the module with updated place-order mixin.

Please let us know if the fix works for you.

**Comment by tobiasolge** [comment]
Hi, looks good in staging. I will try in production later on.
Thanks!

**Comment by tobiasolge** [comment]
Hi,

the update broke our subscription module. there is the following error, when the module tries to generate the order:
Rolled back transaction has not been completed correctly.

**Comment by mam08ixo** [comment]
Hi @tobiasolge, if the original problem has been solved, then please close the issue.

If you experience other problems, then please provide detailed steps how to reproduce – and how the DHL module is involved in causing it – via a new issue or the support channel. The given error message is not something we can work with.

Thank you
