### ISSUE TITLE
DHL module breaks 3rd party module after Update to newest version

### ISSUE THREAD

**Issue by tobiasolge** [netresearch/module-shipping-ui#9]
Hi,

after solving 3D Secure problem (https://github.com/netresearch/module-shipping-ui/issues/8) a new issue occured.

Compatibility with Magedelight SubscribeNow module is broken. After the update, the subscription module is unable to generate orders.
Order generation fails with the following error:

Error: Rolled back transaction has not been completed correctly.

Kind regards.
Tobias

**Comment by mam08ixo** [comment]
Hi @tobiasolge, please explain how the UI-integration module causes a backend database error. We do not have access to the third-party module. You will have to inspect the stack trace and database logs to see which statement in the transaction could not be executed and why.

I assume you are testing Stripe + MageDelight integration. It may be worth testing different Stripe scenarios (success/fail, 3DS yes/no, …) or a different payment method to see if the error can be reliably reproduced or in which cases the transaction succeeds.

Thank you

**Comment by tobiasolge** [comment]
Hi,

the problem is not related to stripe. Normal checkout is possible. Only when module is generating recurring orders, the error apears.

When I remove dhl/shipping-m2 everything works fine. The problem is not solved by disabling shipping-ui.

Kind regards.

**Comment by tobiasolge** [comment]
sorry, reopened here: https://github.com/netresearch/dhl-shipping-m2/issues/62
